myshopfurniture-docker-master/api/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from api import views
from api.views import *
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^moduli/$', api_moduli, name='api-moduli'),
    url(r'^negozi/$', api_negozi, name='api-negozi'),
    url(r'^composizioni/$', api_composizioni, name='api-composizioni'),
   ]
   

myshopfurniture-docker-master/djangocommerce/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from sito import views
from sito.views import *
from django.conf import settings
from django.conf.urls.static import static
from sito.forms import LoginForm

from django.contrib.auth import views
from sito.forms import LoginForm








urlpatterns = [
    url(r'', include('sito.urls')),
    ## api
    url(r'api/', include('api.urls')),
    #login
    url(r'^login/$', views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
    url(r'^logout/$', views.logout, {'next_page': '/login'}), 
    #admin
    url(r'^nested_admin/', include('nested_admin.urls')),
    #url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)), # admin site
]

if settings.DEBUG:  
        urlpatterns += patterns('',  
                                #REMOVE IT in production phase  
                                (r'^media/(?P<path>.*)$', 'django.views.static.serve',  
                                {'document_root': settings.MEDIA_ROOT})
          )

myshopfurniture-docker-master/sito/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from sito import views
from sito.views import *
from blog.views import *
from django.conf import settings
from django.conf.urls.static import static
from sito.forms import LoginForm
import importlib

from django.views.generic import TemplateView




urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', HomePage, name='home'),
    url(r'^demo/$', DemoHomePage, name='home-demo'),
    url(r'^(?P<language>[a-z\-]+)/product/(?P<post_id>\d+)/$', views.ProductFilterView, name='detail'),
    url(r'^(?P<language>[a-z\-]+)/category/(?P<post_id>\d+)/$', views.ProductFilterCategory, name='categoria'),
    # personalizzazione
    url(r'^(?P<language>[a-z\-]+)/personalizzazione/(?P<post_id>\d+)/$', views.Personalizzazione, name='personalizzazione'),
    url(r'^add-personalizzazione/$', views.add_personalizzazione, name='personalizzazione-add'),
    # richiesta
    url(r'^richiesta/$', views.add_richiesta, name='richiesta'),
    #cart
    url(r'^add-to-cart/$', views.add, name='add-to-cart'),
    url(r'^show-cart/$', views.show, name='show-cart'),
    url(r'^remove-cart/(?P<post_id>\d+)/$', views.remove, name='remove-cart'),
    #order
    url(r'^addorder/$', views.add_to_order, name='add-order'),
    url(r'^order/$', views.order, name='order'),
    url(r'^order/(?P<post_id>\d+)/$', views.orderDetail, name='order-detail'),
    # customer
    url(r'^customer/$', views.customer_page, name='customer'),
    url(r'^add_fatturazionecustomer/$', views.add_customer_fatturazione, name='add-fatturazione'),
    url(r'^add_indirizzo_spedizione/$', views.add_customer_indirizzo_spedizione, name='add-indirizzo-spedizione'),
    url(r'^update_fatturazionecustomer/(?P<pk>\d+)/$', views.update_customer_fatturazione, name='update-fatturazione'),
    url(r'^update_indirizzo_spedizione/(?P<pk>\d+)/$', views.update_customer_indirizzo_spedizione, name='update-indirizzo-spedizione'),
    ## cerca
    url(r'^results/$', views.search, name="risultati"),
    ## video
    url(r'^(?P<language>[a-z\-]+)/video/$', views.video, name='video'),
    ## page
    url(r'^(?P<language>[a-z\-]+)/page/(?P<post_id>\d+)/$', views.PageDetail, name='pagina-dettaglio'),
    url(r'^(?P<language>[a-z\-]+)/finiture/$', views.finiture, name='finiture'),
    ## blog
    url(r'^(?P<language>[a-z\-]+)/blog/$', blogView, name='blog'),
    url(r'^(?P<language>[a-z\-]+)/blog/(?P<post_id>\d+)/$', blogDetail, name='blog-dettaglio'),
    #login
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^register/$', views.register_user_page, name="registra-utente"),
    url(r'^add-user/$', views.add_user, name="add-user"),
    ## pagine statiche
    url(r'^contact/$', views.contact, name='contact'),
    url(r'^contact-home/$', views.contactHome, name='contact-home'),
    url(r'^add-newsletter/$', views.add_newsletter, name='add-newsletter'),
    url(r'^sitemap\.xml$', TemplateView.as_view(template_name='sitemap.xml', content_type='text/xml')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/xml')),
    url(r'^language/(?P<language>[a-z\-]+)/$', views.language),
    ## edit language ###################
    url(r'^product/(?P<post_id>\d+)/$', views.ProductFilterViewdue, name='detail-lang'),
    url(r'^category/(?P<post_id>\d+)/$', views.ProductFilterCategorydue, name='categoria-lang'),
    url(r'^video/$', views.videodue, name='video-lang'),
    ## page
    url(r'^page/(?P<post_id>\d+)/$', views.PageDetaildue, name='pagina-dettaglio-lang'),
    url(r'^finiture/$', views.finituredue, name='finiture-lang'),
    ## blog
    url(r'^blog/$', blogViewdue, name='blog-lang'),
    url(r'^blog/(?P<post_id>\d+)/$', blogDetaildue, name='blog-dettaglio-lang'),
   ]

myshopfurniture-docker-master/blog/models.py
from __future__ import unicode_literals
from django.db import models
from image_cropping import ImageRatioField, ImageCropField
from datetime import datetime, timedelta, time, date
from django.utils.timesince import timesince
from filer.fields.image import FilerImageField
from filer.fields.file import FilerFileField
from filer.fields.folder import FilerFolderField
from taggit.managers import TaggableManager
from tinymce.models import HTMLField
from django.utils import timezone
from django import forms

from product.models import *

from filer.fields.image import FilerImageField
from filer.fields.file import FilerFileField

# Create your models here.

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name="Titolo")
    title_uk = models.CharField(max_length=100, verbose_name="Titolo UK")
    image = models.ImageField(blank=True, null=True, upload_to='slider')
    body = models.TextField(null=True, blank=True, verbose_name="Descrizione")
    body_uk = models.TextField(null=True, blank=True, verbose_name="Descrizione UK")
    link = models.TextField(null=True, blank=True)
    slider = ImageRatioField('image', '1000x300', verbose_name="Gallery in Home")
    video = models.TextField(null=True, blank=True, verbose_name="Video")
    album = FilerFolderField(null=True, blank=True)
    pub_date = models.DateTimeField('date published')
    active = models.BooleanField('attiva',
                                    default=False)
    chiavi = models.TextField(null=True, blank=True, verbose_name="Parole Chiave")

    def image_img(self):
        if self.image:
            return u'<img src="%s" style="width:300px"/>' % self.image.url
        else:
            return '(Sin imagen)'
    image_img.short_description = 'Thumb'
    image_img.allow_tags = True

    def __unicode__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Blog"
        ordering = ['id']

myshopfurniture-docker-master/order/models.py
from __future__ import unicode_literals
from django.db import models
from image_cropping import ImageRatioField, ImageCropField
from datetime import datetime, timedelta, time, date
from django.utils.timesince import timesince
from filer.fields.image import FilerImageField
from filer.fields.file import FilerFileField
from filer.fields.folder import FilerFolderField
from taggit.managers import TaggableManager
from tinymce.models import HTMLField
from django.utils import timezone
#from product.forms import *

from product.models import *
from customer.models import *
from order.models import *


from django.contrib.auth.models import User

from django import forms
from django.forms import ModelForm



class Order(models.Model):
	user = models.ForeignKey(User, null=True, blank=True, verbose_name="Utente")
	code = models.CharField('Codice', max_length=250, null=True, blank=True)
	tot_price = models.DecimalField('Prezzo', max_digits=10, decimal_places=2, blank=True, null=True, default=0)
	pub_date = models.DateTimeField('date published', editable=False)
	inlavorazione = models.BooleanField('in lavorazione', default=False)
	pagato = models.BooleanField('pagato', default=False)
	spedito = models.BooleanField('spedito', default=False)
	chiuso = models.BooleanField('chiuso', default=False)

	def ivato(self):
		iva = self.tot_price * 22/100
		ivato = self.tot_price + iva
		return ivato

	def save(self, *args, **kwargs):
		self.pub_date = datetime.now()
		super(Order, self).save(*args, **kwargs) # Call the "real" save() method.

	def __unicode__(self):
		return self.pub_date.strftime('%Y-%m-%d')

	class Meta:
		verbose_name_plural = "Ordine"
		ordering = ['id']




class OrderItem(models.Model):
	order = models.ForeignKey(Order, null=True, blank=True, verbose_name="Ordine")
	product = models.ForeignKey(Product, null=True, blank=True, verbose_name="Prodotto")
	#prezzo
	price = models.DecimalField('Prezzo', max_digits=10, decimal_places=2, blank=True, null=True)
	price_total = models.DecimalField('Prezzo', max_digits=10, decimal_places=2, blank=True, null=True)
	quantity = models.IntegerField(blank=True, null=True, verbose_name="quantita")
	pub_date = models.DateTimeField('date published', editable=False)

	def save(self, *args, **kwargs):
		self.pub_date = datetime.now()
		self.price_total = self.price * self.quantity ## ok ok ok 
		super(OrderItem, self).save(*args, **kwargs) # Call the "real" save() method.

	def __unicode__(self):
		return self.pub_date.strftime('%Y-%m-%d')

	class Meta:
		verbose_name_plural = "Prodotti in Ordine"
		ordering = ['id']




class AddOrderForm(ModelForm):
    class Meta:
        model = Order
        fields = ['user', 'tot_price']



class AddOrderItemForm(ModelForm):
	class Meta:
		model = OrderItem
		fields = ['order', 'product', 'quantity', 'price', 'price_total']



##### PERSONALIZZA ################
class Personalizza(models.Model):
	#user = models.ForeignKey(User, null=True, blank=True, verbose_name="Utente")
	product = models.ForeignKey(Product, null=True, blank=True, verbose_name="Prodotto")
	metriq = models.IntegerField(blank=True, null=True, verbose_name="Metri Quadri Locale")
	email_user = models.CharField('email user', max_length=250, null=True, blank=True)
	user_indirizzo = models.TextField('indirizzo', null=True, blank=True)
	pub_date = models.DateTimeField('date published', editable=False)
	inlavorazione = models.BooleanField('in lavorazione', default=False)
	chiuso = models.BooleanField('chiuso', default=False)

	def save(self, *args, **kwargs):
		self.pub_date = datetime.now()
		super(Personalizza, self).save(*args, **kwargs) # Call the "real" save() method.

	def __unicode__(self):
		return self.pub_date.strftime('%Y-%m-%d')

	class Meta:
		verbose_name_plural = "Personalizzazione"
		ordering = ['id']



class PersonalizzaItem(models.Model):
	personalizza = models.ForeignKey(Personalizza, null=True, blank=True, verbose_name="Personalizza")
	moduli = models.ForeignKey(Moduli, null=True, blank=True, verbose_name="Moduli")
	#prezzo
	quantity = models.IntegerField(blank=True, null=True, verbose_name="quantita")
	pub_date = models.DateTimeField('date published', editable=False)

	def save(self, *args, **kwargs):
		self.pub_date = datetime.now()
		super(PersonalizzaItem, self).save(*args, **kwargs) # Call the "real" save() method.

	def __unicode__(self):
		return self.pub_date.strftime('%Y-%m-%d')

	class Meta:
		verbose_name_plural = "Personalizzazione Item"
		ordering = ['id']



class AddPersonalizzaForm(ModelForm):
    class Meta:
        model = Personalizza
        fields = ['product', 'metriq', 'email_user', 'user_indirizzo']



class PersonalizzaItemForm(ModelForm):
	class Meta:
		model = PersonalizzaItem
		fields = ['personalizza', 'moduli', 'quantity']

myshopfurniture-docker-master/sito/forms.py
from django.contrib.auth.forms import AuthenticationForm 
from django import forms

class LoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30, 
                               widget=forms.TextInput(attrs={'class': 'form-control', 'name': 'username'}))
    password = forms.CharField(label="Password", max_length=30, 
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'name': 'password'}))

myshopfurniture-docker-master/blog/views.py
# coding=utf-8
from django.shortcuts import render
from django.shortcuts import render_to_response, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template import RequestContext
from django.views.generic import ListView, DetailView
from django.template.loader import render_to_string
from blog.models import *
from filer.models import *
# Create your views here.


def blogView(request, language):
	blog_list = Blog.objects.all().order_by('-pub_date')
	context = {'blog_list':blog_list}
	return render_to_response('blog.html', context, context_instance=RequestContext(request))

def blogDetail(request, post_id, language):
	blog = Blog.objects.get(pk=post_id)
	context = {'blog':blog}
	return render_to_response('blog-detail.html', context, context_instance=RequestContext(request))

def blogViewdue(request):
	blog_list = Blog.objects.all().order_by('-pub_date')
	context = {'blog_list':blog_list}
	return render_to_response('blog.html', context, context_instance=RequestContext(request))

def blogDetaildue(request, post_id):
	blog = Blog.objects.get(pk=post_id)
	context = {'blog':blog}
	return render_to_response('blog-detail.html', context, context_instance=RequestContext(request))

myshopfurniture-docker-master/customer/views.py
from django.shortcuts import render

# Create your views here.

myshopfurniture-docker-master/sito/templates/blog.html
blog.html

myshopfurniture-docker-master/sito/templates/iban_emailuk.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>ORDINE</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <style type="text/css">
#footer a,
#footer a:link {
	color: #ffffff;
}
  </style>
    <body>





<div class="container" style="background-color: #ffffff; width:800px;">
	<div class="col-xs-12" style="background-color:#000000; height:40px;"><br></div>
	<br>
	<br>
	<br>
	<span style="text-align: center; margin-top: 30px; margin-bottom:30px;"><img src="http://www.myshopfurniture.com/static/img/logo.png" style="width: 400px;"></span>
	<br>
	<br>

	<div class="col-xs-12" style="margin-left:0px; padding-left:0px;">
		<div class="col-xs-8" style="margin-left:0px; padding-left:0px;">
			<h5 style="background-color: #d9d9d9; padding:5px;">Request effectuated: {{ordine.pub_date}}</h5>
			<h5 style="background-color: #d9d9d9; padding:5px;">ID order: {{ordine.id}}</h5>
			<!--h5 style="background-color: #d9d9d9; padding:5px;">da: {{ordine.user.username}}</h5-->
		</div>
		<div class="col-xs-4"></div>
	</div>

	<div class="col-xs-6" style="margin-left:0px; padding-left:0px;">
		<p style="padding-left:0px; text-align: left">
			{% if consegna %}
			<br>
			<br>
			<strong>Delivery Address</strong><br>
			{{consegna.first.spedizione_denominazione}}<br>
			{{consegna.first.spedizione_indirizzo}}<br>
			{{consegna.first.spedizione_cap}} - {{consegna.first.spedizione_citta}}<br>
			Tel. {{consegna.spedizione_telefono}}<br>
			email. {{fatturazione.user.email}}<br>
			<br>
			{% endif %}
		</p>
	</div>

	<div class="col-xs-6">
		<p style="text-align: right">
			<br>
			<br>
			<strong>Customer Data</strong><br>
			{{fatturazione.denominazione}}<br>
			{{fatturazione.indirizzo}}<br>
			{{fatturazione.cap}} - {{fatturazione.citta}}<br>
			Tel. {{fatturazione.telefono}}<br>
			email. {{fatturazione.user.email}}<br>
			<br>
		</p>
	</div>
	
	<div class="col-xs-12" style="padding-left:0px; padding-right:0px;">
		<h5 style="background-color: #dfdb00; padding-left:15px;">
			<br>
			The order will be confirmed upon receipt of payment to be made to the following account:<br>
			<br>
			Credito Bergamasco:<br>
			Beneficiary: GLOCAL s.r.l. <br>
			SWIFT/BIC: BAPPIT21AM9<br>
			IBAN: IT13G0503453760000000000681<br>
			causal: Order N. {{ordine.id}}
			<br>&nbsp;
			<br>
			Totale: €. {{ordine.ivato}}
			<br>
			<br>&nbsp;
		</h5>
	</div>
	{% for item in ordine.orderitem_set.all %}
	{% load cropping %}
	<img src="{% cropped_thumbnail item.product "slider" %}" class="img-responsive">  
	<!--img src="http://test.myshopfurniture.com/media/{{personalizza.product.image}}" class="img-responsive"-->
	
	<h2>{{item.product.name}}</h2>
	<h4>Materiale: {{item.product.color.first}}</h4><br>
	<table class="table table-striped">
	  <tr>
	      <th>img</th>
	      <th>Modulo</th>
	      <th>Quantità</th>
	  </tr>

	 {% for mod in item.product.composition_set.all %}
	  <tr>
	    <td>
	      {% load cropping %}
	      <img src="http://www.myshopfurniture.com/media/{{mod.modulo.image}}" style="width:200" width="200">
	    </td>
	    <td>
	    	<strong>{{mod.name_uk}}</strong><br><br>
	    	<strong>Size:</strong><br>
			{% if mod.modulo.width %}<strong>Width:</strong> {{mod.modulo.width}} | {% endif %}
			{% if mod.modulo.depth %}<strong>depth:</strong> {{mod.modulo.depth}} | {% endif %}
			{% if mod.modulo.height %}<strong>Height:</strong> {{mod.modulo.height}} | {% endif %}
	    </td>
	    <td>{{mod.quantity}}</td>
	  </tr>
	{% endfor %}
	</table>
{% endfor %}
<br>
<br>
<br>
<br>

<div id="footer" class="col-xs-12" style="background-color:#000000;padding-top:20px;padding-bottom:50px;">
	<div class="col-xs-4">
		<img src="http://www.myshopfurniture.com/static/img/logo_bianco.png" class="img-responsive">
	</div>
	<div class="col-xs-8">
		<p style="color:#ffffff; float:right;">
			myshopfurmiture.com
		</p>
	</div>
</div>
</div>

    </body>
</html>

myshopfurniture-docker-master/sito/templates/orderdetail.html
{% extends 'base.html' %}

{% block yellowline %}
<div class="col-xs-12 banding-yellow"></div>
{% endblock %}

{% block content %}

<div class="container" style="background-color: #ffffff; margin-bottom:0px;">

<div style="width:95%; margin: 0 auto; margin-bottom:200px;margin-top:20px;">

<h5 style="margin-top:20px;">
  <br>
  {% if session_language = 'en' %}
  Hello {{request.user.username }}, this is your order made in date {{order.pub_date}}
  {% else %}
  Ciao {{request.user.username }}, questo è il tuo ordine effettuato in data {{order.pub_date}}
  {% endif %}
  <br>
  <br>ID ORDINE: {{order.id}}</h5>
<br>
<table class="table table-striped">
  <tr>
      <th>Img/{% if session_language = 'en' %}Detail{% else %}Dettaglio{% endif %}</th>
      <th>{% if session_language = 'en' %}Product{% else %}Prodotto{% endif %}</th>
      <th>{% if session_language = 'en' %}Color{% else %}Colore{% endif %}</th>
      <th></th>
      <th class="hidden-xs hidden-sm">{% if session_language = 'en' %}Quantity{% else %}Quantità{% endif %}</th>
      <th class="hidden-md hidden-lg">Qt.</th>
      <th class="hidden-xs hidden-sm hidden-md">{% if session_language = 'en' %}Price Unit{% else %}Prezzo Unitario{% endif %}</th>
      <th class="hidden-xs hidden-sm">{% if session_language = 'en' %}Total Price{% else %}Prezzo Totale{% endif %}</th>
      <th class="hidden-md hidden-lg">{% if session_language = 'en' %}Tot.Price{% else %}Prezzo Tot.{% endif %}</th>
      <th></th>
  </tr>

 {% for cart in order.orderitem_set.all %}
  <tr>
    <td>
      {% load cropping %}
      	<a href="{% url 'detail' session_language cart.product.id %}">
      		<img src="{% cropped_thumbnail cart.product "thumbdue" %}" style="width:200px;" class="hidden-xs hidden-sm">
          <img src="{% cropped_thumbnail cart.product "thumbdue" %}" style="width:130px;" class="hidden-md hidden-lg">
  		</a>
    </td>
    <td>
       {% if session_language = 'en' %}
            {{cart.product.name_uk}}
       {% else %}
           {{cart.product.name}}
        {% endif %}
    </td>
    
    <td>
      {% if cart.product.color %}
      <p>
        <span style="font-size:10px;">
          <img src="/media/{{cart.product.color.first.image}}" class="color-thumb-circle" style="width:30px;height:30px; border-radius:30px;">
           <span class="hidden-xs hidden-sm">{{cart.product.color.first}}</span>
        {% endif %}
        </span>
      </p>
    </td>
    
    <td>

    </td>

    <td>{{cart.quantity}}</t>
    <td class="hidden-xs hidden-sm hidden-md">{{cart.price}} €.</td>
    <td>
      <span class="hidden-sm hidden-xs">{% if session_language = 'en' %}Total:{% else %}Totale:{% endif %}</span> {{cart.price_total}} €.<br>
    </td>
    <td></td>
  </tr>
{% endfor %}



</table>
<span class="hidden-lg hidden-md"><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br></span>

    </div>

</div>



{% endblock %}

myshopfurniture-docker-master/sito/templates/personalizza_email.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>ORDINE</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </head>

  <style type="text/css">
#footer a,
#footer a:link {
	color: #ffffff;
}
  </style>
    <body>





<div class="container" style="background-color: #ffffff; width:800px;">
	<div class="col-xs-12" style="background-color:#000000; height:40px;"><br></div>
	<br>
	<br>
	<br>
	<span style="text-align: center; margin-top: 30px; margin-bottom:30px;"><img src="http://www.myshopfurniture.com/static/img/logo.png" style="width: 400px;"></span>
	<br>
	<br>
	
	<h5 style="background-color: #dfdb00; padding:10px; border-radius:10px;">
		Richiesta effettuata in data {{personalizza.pub_date}}<br>
	</h5>

	<h5 style="background-color: #cccccc; padding:10px; border-radius:10px;">
		Metri Quadri Locale: {{personalizza.metriq}}
	</h5>
	<br>
	<h5>
		email: {{personalizza.email_user}}<br>
		<br>
		<strong>indirizzo:</strong><br>
		{{personalizza.user_indirizzo}}
		<br>
	</h5>
	{% load cropping %}
	<img src="{% cropped_thumbnail personalizza.product "slider" %}" class="img-responsive">  
	<!--img src="http://test.myshopfurniture.com/media/{{personalizza.product.image}}" class="img-responsive"-->
	
	<h2>{{personalizza.product.name}}</h2>
	
	<table class="table table-striped">
	  <tr>
	      <th>img</th>
	      <th>Modulo</th>
	      <th>Quantità</th>
	  </tr>

	 {% for mod in personalizza.personalizzaitem_set.all %}
	  <tr>
	    <td>
	      {% load cropping %}
	      <img src="http://www.myshopfurniture.com/media/{{mod.moduli.image}}" style="width:200" width="200">
	    </td>
	    <td>
	    	<strong>{{mod.moduli.name}}</strong>
	    	<strong>Dimensioni:</strong><br>
			{% if mod.moduli.width %}<strong>Larghezza:</strong> {{mod.moduli.width}} | {% endif %}
			{% if mod.moduli.depth %}<strong>Profondità:</strong> {{mod.moduli.depth}} | {% endif %}
			{% if mod.moduli.height %}<strong>Altezza:</strong> {{mod.moduli.height}} | {% endif %}
	    </td>
	    <td>{{mod.quantity}}</td>
	  </tr>
	{% endfor %}



	</table>

	<h5 class="text-right">
	  Metri Quadri Locale: {{personalizza.metriq}}
	</h5>


</div>

   <div id="footer" class="col-xs-12" style="background-color:#000000;padding-top:20px;padding-bottom:50px;">
	<div class="col-xs-4">
		<img src="http://www.myshopfurniture.com/static/img/logo_bianco.png" class="img-responsive" style="width:200px">
	</div>
	<div class="col-xs-8">
		<p style="color:#ffffff; float:right;">
			myshopfurmiture.com
		</p>
	</div>
</div>
</div>

</body>
</html>